### ISSUE TITLE
Mod Compability - Vampirism

### ISSUE THREAD

**Issue by maxanier** [Razmen/HowlingMoon#4]
Hello Razmen,

I'm the author of the Vampirism mod, which allows players to become a vampire (or a vampire hunter).
A frequently requested thing is some kind of compatibility with your Howling Moon mod.
At least preventing players from becoming both a vampire and a werewolf at the same time would be cool.

Is there any way I can find out, if a player is a werewolf or is infected (code wise)?

Many Thanks,
Maxanier

**Comment by WolvzUnion** [comment]
i have no clue what type of programming is used to make mods and i can barely do java script so the least i can do is give u the code for the 2 mods via opening it with notepad sorry

**Comment by Razmen** [comment]
A API for the mod is being released in the next update this month. And I'll possibly adding some extra compatibility with mods like Vampirism in another update.
